# Generated by Django 4.0.6 on 2022-07-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='contents',
            field=models.CharField(default='', max_length=5000, null=True),
        ),
    ]
